superheroesdb/superheroesapp/urls.py
from django.urls import path
from . import views


app_name = 'superheroesapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='details'),
    path('create/', views.create, name='create'),
    path('edit/', views.edit, name='edit'),
]

superheroesdb/superheroesdb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroesapp/', include('superheroesapp.urls')),
    path('', RedirectView.as_view(url='/superheroesapp/'))
]

superheroesdb/superheroesapp/models.py
from django.db import models
from django.db.models.fields import CharField

# Create your models here.


class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_superpower = models.CharField(max_length=50)
    secondary_superpower = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superheroesdb/superheroesapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Superhero
from django.urls import reverse

# Create your views here.


def index(request):
    all_superheroesapp = Superhero.objects.all()
    context = {
        'all_superheroesapp': all_superheroesapp
    }
    return render(request, 'superheroesapp/index.html', context)


def detail(request, superhero_id):
    selected_hero = Superhero.objects.get(pk=superhero_id)
    context = {
        'selected_hero': selected_hero
    }
    return render(request, 'superheroesapp/details.html', context)


def edit(request, superhero_id):
    superhero_delete = Superhero.objects.get(pk=superhero_id)
    context = {
        'superhero_delete': superhero_delete
    }
    return render(request, 'superheroesapp/edit.html', context)


def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_superpower = request.POST.get('primary_superpower')
        secondary_superpower = request.POST.get('secondary_superpower')
        catchphrase = request.POST.get('catchphrase')
        new_superhero = Superhero(name=name, alter_ego=alter_ego, primary_superpower=primary_superpower,
                                  secondary_superpower=secondary_superpower, catchphrase=catchphrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroesapp:index'))
    else:
        return render(request, 'superheroesapp/create.html')

superheroesdb/superheroesapp/templates/superheroesapp/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create-A-Hero</title>
</head>

<body>
    <form action="{% url 'superheroesapp:create' %}" method="post">
        {% csrf_token %}
        Name:<input type="text" name="name" id="name"><br>
        Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
        Primary Superpower:<input type="text" name="primary_superpower" id="primary_superpower"><br>
        Secondary Superpower:<input type="text" name="secondary_superpower" id="secondary_superpower"><br>
        Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br>
        <input type="submit" value="Create my superhero" <p>
        <a href="{% url 'superheroesapp:index' %}">Home</a>
        </p>

    </form>
</body>

</html>

superheroesdb/superheroesapp/templates/superheroesapp/details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Deets</title>
</head>

<body>
    <div class="container-fluid">
        <center>
            <div class="row">
                <div>
                    <h1>Superhero Details</h1><br /><br />
                </div>
                <div>
                    <h1>{{selected_hero.name}}</h1>
                    <table border="1">
                        <tr>
                            <th>Alter Ego</th>
                            <th>Primary Ability</th>
                            <th>Secondary Ability</th>
                            <th>Catchphrase</th>
                        </tr>
                        <tr>
                            <td>{{selected_hero.alter_ego}}</td>
                            <td>{{selected_hero.primary_superpower}}</td>
                            <td>{{selected_hero.secondary_superpower}}</td>
                            <td>{{selected_hero.catchphrase}}</td>
                        </tr>
                        <button><a href=>Delete</a>


                    </table>
                </div>

</body>

</html>

superheroesdb/superheroesapp/templates/superheroesapp/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Edit Superhero</title>
</head>

<body>
    <form action="{% url 'superheroesapp:edit' superhero_edit.id %}" method="post">
        {% csrf_token %}
        Name:<input type="text" name="name" id="name"><br>
        Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
        Primary Super Power:<input type="text" name="primary_superpower" id="primary_superpower"><br>
        Secondary Super Power:<input type="text" name="secondary_superpower" id="secondary_superpower"><br>
        Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br>
        <input type="submit" value="Edit Superhero">
        <p>
            <a href="{% url 'superheroesapp:index' %}">Home</a>
        </p>
    </form>
</body>

</html>

superheroesdb/superheroesapp/templates/superheroesapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>

<body>
    <h1>Superheroes:</h1>
    <ul>
        {% for superhero in all_superheroesapp %}
        <li>
            <h2> {{superhero.name}}</h2>
            <a href="{% url 'superheroesapp:details' superhero.id %}">Click for details</a>
        </li>
        {% endfor %}
    </ul>
    <p>
    <ul>
        <h2>Additional Options:</h2>
        <li><a href="{% url 'superheroesapp:create' %}">Create</a> your own superhero.</li>
        <li><a href="{% url 'superheroesapp:edit' %}">Edit</a> superhero.</li>
    </ul>
    <p>
        <img src="templates/superheroesapp/deadpool.jpg">
    </p>
</body>

</html>

superheroesdb/superheroesapp/templates/superheroesapp/remove.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Deleted</title>
</head>

<body>
    <h1>Superhero has been deleted.</h1>
    <p><a href="{% url 'superheroesapp:create' %}">Add new hero?</a></p>
</body>

</html>